# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.api.performance_templates_api import PerformanceTemplatesApi


class TestPerformanceTemplatesApi(unittest.TestCase):
    """PerformanceTemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PerformanceTemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_device_type2_get_all_performance_policies(self) -> None:
        """Test case for device_type2_get_all_performance_policies

        Get all performance-policies details by Nimble / Alletra 6K
        """
        pass

    def test_device_type2_get_performance_policy_by_id(self) -> None:
        """Test case for device_type2_get_performance_policy_by_id

        Get details of Nimble / Alletra 6K performance-policy identified by {performancePolicyId}
        """
        pass

    def test_device_type2_performance_policy_create(self) -> None:
        """Test case for device_type2_performance_policy_create

        Create Nimble / Alletra 6K performance policy in a system identified by {systemId}
        """
        pass

    def test_device_type2_performance_policy_edit(self) -> None:
        """Test case for device_type2_performance_policy_edit

        Edit details of Nimble / Alletra 6K performance policy identified by {performancePolicyId}
        """
        pass

    def test_device_type2_remove_perf_policy_id(self) -> None:
        """Test case for device_type2_remove_perf_policy_id

        Remove performance-policies identified by {performancePolicyId} from Nimble / Alletra 6K
        """
        pass


if __name__ == '__main__':
    unittest.main()
