# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.appset_post import AppsetPost

class TestAppsetPost(unittest.TestCase):
    """AppsetPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppsetPost:
        """Test AppsetPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppsetPost`
        """
        model = AppsetPost()
        if include_optional:
            return AppsetPost(
                comment = '',
                expire_secs = 100,
                read_only = False,
                retain_secs = 86400,
                snapshot_name = 'snapshot_oracle_1611807822',
                vv_name_pattern = 'PARENT_TIMESTAMP'
            )
        else:
            return AppsetPost(
                snapshot_name = 'snapshot_oracle_1611807822',
                vv_name_pattern = 'PARENT_TIMESTAMP',
        )
        """

    def testAppsetPost(self):
        """Test AppsetPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
