# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.start_params import StartParams

class TestStartParams(unittest.TestCase):
    """StartParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartParams:
        """Test StartParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartParams`
        """
        model = StartParams()
        if include_optional:
            return StartParams(
                skip_initial_sync = True,
                target_name = 's1511'
            )
        else:
            return StartParams(
        )
        """

    def testStartParams(self):
        """Test StartParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
