# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.device_type4_vluns_create_input import DeviceType4VlunsCreateInput

class TestDeviceType4VlunsCreateInput(unittest.TestCase):
    """DeviceType4VlunsCreateInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceType4VlunsCreateInput:
        """Test DeviceType4VlunsCreateInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceType4VlunsCreateInput`
        """
        model = DeviceType4VlunsCreateInput()
        if include_optional:
            return DeviceType4VlunsCreateInput(
                lun = [
                    dscc.models.device_type4_vluns_create_input_lun_inner.DeviceType4VlunsCreateInput_LUN_inner(
                        lun = 34, 
                        host_group_id = 'cb17544e9347145d22a0fac608831053', 
                        nvme_transport_type = 'TCP', )
                    ],
                auto_lun = True,
                host_group_ids = [
                    ''
                    ],
                max_auto_lun = 1,
                no_vcn = True,
                override = True,
                position = 'position_1',
                proximity = 'PRIMARY'
            )
        else:
            return DeviceType4VlunsCreateInput(
                host_group_ids = [
                    ''
                    ],
        )
        """

    def testDeviceType4VlunsCreateInput(self):
        """Test DeviceType4VlunsCreateInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
