# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.enclosure_card_port_details import EnclosureCardPortDetails

class TestEnclosureCardPortDetails(unittest.TestCase):
    """EnclosureCardPortDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnclosureCardPortDetails:
        """Test EnclosureCardPortDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnclosureCardPortDetails`
        """
        model = EnclosureCardPortDetails()
        if include_optional:
            return EnclosureCardPortDetails(
                associated_links = [{"resourceUri":"/v1/storage-systems/device-type1/2FF70002AC01F0FF","type":"systems"},{"resourceUri":"/v1/storage-systems/device-type1/2FF70002AC01F0FF/enclosures/9c3c4f29a82fd8d632ff379116fa0b8f","type":"enclosures"}],
                common_resource_attributes = dscc.models.primera_common_resource_attributes.primeraCommonResourceAttributes(
                    cloud_state = 'CONNECTED', ),
                console_uri = 'data-ops-manager/storage-systems/device-type1/SGH014XGSP/enclosures/9c3c4f29a82fd8d632ff379116fa0b8f/enclosure-card-ports/8621946048c1cb24bdfc57e9b3b460ac',
                customer_id = 'string',
                dc4data = dscc.models.ecp_dc4data.ecpDc4data(
                    link_rx_led = 'LED_UNKNOWN', 
                    link_tx_led = 'LED_UNKNOWN', ),
                dcsdata = dscc.models.ecp_dcsdata.ecpDcsdata(
                    sas_link_enabled = True, 
                    sas_link_online = True, ),
                disabled = True,
                displayname = 'Drive Enclosure - 0, IO Module - 0, Port - DP-1',
                domain = '',
                element_status_code = '',
                enclosure_card_device_id = 1,
                enclosure_card_id = '4c592313a65224f9dc804ca4ced2b88b',
                enclosure_card_port_id = 0,
                enclosure_card_port_type = 'External',
                enclosure_device_id = 1,
                enclosure_id = '9c3c4f29a82fd8d632ff379116fa0b8f',
                enclosure_name = '',
                enclosure_type = 'ENCLOSURE_DCS8',
                generation = 0,
                id = '9c3c4f29a82fd8d632ff379116fa0b8f',
                link_speed = '',
                locate_enabled = False,
                loop_a = False,
                loop_index = 2,
                node_port = dscc.models.enc_port_position.encPortPosition(
                    node = 1, 
                    port = 1, 
                    slot = 1, ),
                os_display_name = 'DP-3',
                port_wwn = '50050CC111510A3E',
                request_uri = '/v1/storage-systems/device-type1/2FF70002AC018D94/enclosures/9c3c4f29a82fd8d632ff379116fa0b8f/enclosure-card-ports/8621946048c1cb24bdfc57e9b3b460ac',
                resource_uri = '/v1/storage-systems/device-type1/2FF70002AC018D94/enclosures/9c3c4f29a82fd8d632ff379116fa0b8f/enclosure-card-ports/8621946048c1cb24bdfc57e9b3b460ac',
                sfp = dscc.models.fc_port_sfp_single.FcPortSfpSingle(
                    fw_version = '', 
                    manufacturing = dscc.models.manufacturing_single.manufacturingSingle(
                        assembly_rev = '002*', 
                        check_sum = '--', 
                        hpe_model_name = 'HPE 3PAR 600 2S Node', 
                        manufacturer = 'XYRATEX', 
                        model = '0974244-06', 
                        saleable_part_number = '0974244-06', 
                        saleable_serial_number = '4UW0002941', 
                        serial_number = 'PMW0974244G4T88', 
                        spare_part_number = 'P04031-001', ), 
                    name = '', 
                    qualified = True, 
                    rx_loss_pin = '', 
                    rx_power_low = True, 
                    speed = 1, 
                    state = dscc.models.state.STATE(
                        detailed = [
                            ''
                            ], 
                        overall = 'STATE_NORMAL', ), 
                    tx_disable_pin = '', 
                    tx_fault_pin = '', ),
                system_id = '7CE751P312',
                type = 'string'
            )
        else:
            return EnclosureCardPortDetails(
        )
        """

    def testEnclosureCardPortDetails(self):
        """Test EnclosureCardPortDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
