# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.nimble_network_interface_fields_without_sort_key import NimbleNetworkInterfaceFieldsWithoutSortKey

class TestNimbleNetworkInterfaceFieldsWithoutSortKey(unittest.TestCase):
    """NimbleNetworkInterfaceFieldsWithoutSortKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NimbleNetworkInterfaceFieldsWithoutSortKey:
        """Test NimbleNetworkInterfaceFieldsWithoutSortKey
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NimbleNetworkInterfaceFieldsWithoutSortKey`
        """
        model = NimbleNetworkInterfaceFieldsWithoutSortKey()
        if include_optional:
            return NimbleNetworkInterfaceFieldsWithoutSortKey(
                array_id = '2a0df0fe6f7dc7bb16000000000000000000004817',
                array_name_or_serial = 'myobject-5',
                id = '2a0df0fe6f7dc7bb16000000000000000000004817',
                mac = '11:33:55:77:99:BB'
            )
        else:
            return NimbleNetworkInterfaceFieldsWithoutSortKey(
        )
        """

    def testNimbleNetworkInterfaceFieldsWithoutSortKey(self):
        """Test NimbleNetworkInterfaceFieldsWithoutSortKey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
