# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.nimble_alarms_with_request_uri import NimbleAlarmsWithRequestUri

class TestNimbleAlarmsWithRequestUri(unittest.TestCase):
    """NimbleAlarmsWithRequestUri unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NimbleAlarmsWithRequestUri:
        """Test NimbleAlarmsWithRequestUri
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NimbleAlarmsWithRequestUri`
        """
        model = NimbleAlarmsWithRequestUri()
        if include_optional:
            return NimbleAlarmsWithRequestUri(
                request_uri = 'api/v1/storage-systems/device-type2/2a0df0fe6f7dc7bb16000000000000000000004817/alarms/2a0df0fe6f7dc7bb16000000000000000000004007',
                ack_time = 3400,
                activity = 'Created snapshot % of volume %',
                alarm_type = 10,
                array = 'AC-109084',
                category = 'unknown',
                curr_onset_event_id = '2a0df0fe6f7dc7bb16000000000000000000004817',
                id = '2a0df0fe6f7dc7bb16000000000000000000004817',
                next_notification_time = 1234,
                object_id = 'volumes in performance policy default',
                object_name = 'volumes in performance policy default',
                object_type = 'group',
                onset_time = 3400,
                remind_every = 10,
                remind_every_unit = 'minutes',
                severity = 'info',
                status = 'open',
                user_full_name = 'User-13 Peterson',
                user_id = '2a0df0fe6f7dc7bb16000000000000000000004817',
                user_name = 'user1, companydomain\user',
                associated_links = [{resourceUri=/api/v1/storage-systems/device-type2/2a0df0fe6f7dc7bb16000000000000000000004817, type=storage-systems}],
                common_resource_attributes = dscc.models.nimble_common_resource_attributes.NimbleCommonResourceAttributes(
                    cloud_state = 'CONNECTED', ),
                console_uri = 'null',
                customer_id = 'string',
                generation = 0,
                resource_uri = '/api/v1/storage-systems/device-type2/2a0df0fe6f7dc7bb16000000000000000000004817',
                summary = '',
                type = 'string'
            )
        else:
            return NimbleAlarmsWithRequestUri(
        )
        """

    def testNimbleAlarmsWithRequestUri(self):
        """Test NimbleAlarmsWithRequestUri"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
