# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.deprecated_device_type4user_allocation_settings_single_ha import DeprecatedDeviceType4userAllocationSettingsSingleHA

class TestDeprecatedDeviceType4userAllocationSettingsSingleHA(unittest.TestCase):
    """DeprecatedDeviceType4userAllocationSettingsSingleHA unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeprecatedDeviceType4userAllocationSettingsSingleHA:
        """Test DeprecatedDeviceType4userAllocationSettingsSingleHA
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeprecatedDeviceType4userAllocationSettingsSingleHA`
        """
        model = DeprecatedDeviceType4userAllocationSettingsSingleHA()
        if include_optional:
            return DeprecatedDeviceType4userAllocationSettingsSingleHA(
                default = 'Magazine',
                key = 'hajbod-10'
            )
        else:
            return DeprecatedDeviceType4userAllocationSettingsSingleHA(
        )
        """

    def testDeprecatedDeviceType4userAllocationSettingsSingleHA(self):
        """Test DeprecatedDeviceType4userAllocationSettingsSingleHA"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
