# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.vluns_create_input_lun_inner import VlunsCreateInputLUNInner

class TestVlunsCreateInputLUNInner(unittest.TestCase):
    """VlunsCreateInputLUNInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VlunsCreateInputLUNInner:
        """Test VlunsCreateInputLUNInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VlunsCreateInputLUNInner`
        """
        model = VlunsCreateInputLUNInner()
        if include_optional:
            return VlunsCreateInputLUNInner(
                lun = 34,
                host_group_id = 'cb17544e9347145d22a0fac608831053'
            )
        else:
            return VlunsCreateInputLUNInner(
        )
        """

    def testVlunsCreateInputLUNInner(self):
        """Test VlunsCreateInputLUNInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
