# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.device_type4_system_capacity_usage import DeviceType4SystemCapacityUsage

class TestDeviceType4SystemCapacityUsage(unittest.TestCase):
    """DeviceType4SystemCapacityUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceType4SystemCapacityUsage:
        """Test DeviceType4SystemCapacityUsage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceType4SystemCapacityUsage`
        """
        model = DeviceType4SystemCapacityUsage()
        if include_optional:
            return DeviceType4SystemCapacityUsage(
                snap_space = 228565.15,
                volume_space = 233359.43
            )
        else:
            return DeviceType4SystemCapacityUsage(
        )
        """

    def testDeviceType4SystemCapacityUsage(self):
        """Test DeviceType4SystemCapacityUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
