# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.volume_capacity_history import VolumeCapacityHistory

class TestVolumeCapacityHistory(unittest.TestCase):
    """VolumeCapacityHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VolumeCapacityHistory:
        """Test VolumeCapacityHistory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VolumeCapacityHistory`
        """
        model = VolumeCapacityHistory()
        if include_optional:
            return VolumeCapacityHistory(
                capacity_data = dscc.models.volume_capacity_history_capacity_data.volumeCapacityHistory_capacityData(
                    customer_id = 'string', 
                    items = [
                        dscc.models.volume_capacity_series_data.volumeCapacitySeriesData(
                            actual_usage_mi_b = 25, 
                            host_written_capacity_mi_b = 20, 
                            timestamp_ms = 1605063600, )
                        ], 
                    total = 1, ),
                common_resource_attributes = dscc.models.primera_common_resource_attributes.primeraCommonResourceAttributes(
                    cloud_state = 'CONNECTED', ),
                end_time = 1625209133,
                request_uri = '/v1/storage-systems/device-type1/SGH014XGSP/volumes/a7c4e6593f51d0b98f0e40d7e6df04fd/capacity-history',
                start_time = 1625122733
            )
        else:
            return VolumeCapacityHistory(
        )
        """

    def testVolumeCapacityHistory(self):
        """Test VolumeCapacityHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
