# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.create_certificate_input import CreateCertificateInput

class TestCreateCertificateInput(unittest.TestCase):
    """CreateCertificateInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCertificateInput:
        """Test CreateCertificateInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCertificateInput`
        """
        model = CreateCertificateInput()
        if include_optional:
            return CreateCertificateInput(
                authority_chain = '-----BEGIN CERTIFICATE REQUEST-----abc----END CERTIFICATE REQUEST-----',
                common_name = 'hpe.com CA - Intermediate',
                country = 'IN',
                days = 365,
                key_length = 2048,
                locality = 'BLR',
                organization = 'HPE',
                organization_unit = 'HPE Primera',
                province = 'Karnataka',
                service = 'QW_CLIENT',
                subject_alt_name = dscc.models.cert_subject_alt_name.certSubjectAltName(
                    dns = '7CE815P2BH', 
                    ip = '15.213.65.129', 
                    email = 'abc@hpe.com', ),
                type = 'csr'
            )
        else:
            return CreateCertificateInput(
                service = 'QW_CLIENT',
                type = 'csr',
        )
        """

    def testCreateCertificateInput(self):
        """Test CreateCertificateInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
