# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.edit_target_partner import EditTargetPartner

class TestEditTargetPartner(unittest.TestCase):
    """EditTargetPartner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditTargetPartner:
        """Test EditTargetPartner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditTargetPartner`
        """
        model = EditTargetPartner()
        if include_optional:
            return EditTargetPartner(
                hostname = '15.213.204.164',
                name = 'replicationPartner2',
                subnet_label = 'myobject-5',
                subnet_type = 'mgmt'
            )
        else:
            return EditTargetPartner(
        )
        """

    def testEditTargetPartner(self):
        """Test EditTargetPartner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
