# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.nimble_ns_shelf_ctrlr_attr_set import NimbleNsShelfCtrlrAttrSet

class TestNimbleNsShelfCtrlrAttrSet(unittest.TestCase):
    """NimbleNsShelfCtrlrAttrSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NimbleNsShelfCtrlrAttrSet:
        """Test NimbleNsShelfCtrlrAttrSet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NimbleNsShelfCtrlrAttrSet`
        """
        model = NimbleNsShelfCtrlrAttrSet()
        if include_optional:
            return NimbleNsShelfCtrlrAttrSet(
                cached_serial = 'AA-100373',
                disk_serials = 'disk_sdf:2:0:0:0,disk_sdg:2:0:1:0,disk_sdh:2:0:2:0,disk_sdi:2:0:3:0,disk_sdj:2:0:4:0,disk_sdk:2:0:5:0,disk_sdb:1:0:0:0,disk_sdc:1:0:1:0,disk_sdd:1:0:2:0,disk_sde:1:0:3:0,disk_sdl:2:0:6:0,disk_sdm:2:0:8:0,disk_sdn:2:0:9:0,disk_sdo:2:0:10:0,disk_sdp:2:0:11:0,disk_sdq:2:0:12:0',
                disk_types = 'WD-WCAW31074925,WD-WCAW31562278,WD-WCAW31543481,WD-WCAW31546957,CVPO105101AQ080JGN,CVPO1051023B080JGN,WD-WCAW31507140,WD-WCAW31545053,WD-WCAW31549016,WD-WCAW31544371',
                hw_state = 'ready',
                session_serial = 'shelf_0_0x5003048000b0567f_1456884624.213307',
                sw_type = 'Disk Shelf'
            )
        else:
            return NimbleNsShelfCtrlrAttrSet(
        )
        """

    def testNimbleNsShelfCtrlrAttrSet(self):
        """Test NimbleNsShelfCtrlrAttrSet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
