# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.mailsettings import Mailsettings

class TestMailsettings(unittest.TestCase):
    """Mailsettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Mailsettings:
        """Test Mailsettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Mailsettings`
        """
        model = Mailsettings()
        if include_optional:
            return Mailsettings(
                associated_links = [{"resourceUri":"/api/v1/storage-systems/device-type1/7CE751P312","type":"systems"}],
                authentication_required = 'enabled',
                console_uri = 'data-ops-manager/storage-systems/device-type1/SGH014XGSP/settings/system-settings',
                customer_id = 'fc5f41652a53497e88cdcebc715cc1cq',
                friendly_cert = dscc.models.friendly_certificate.friendlyCertificate(
                    valid_from = dscc.models.device_type4friendly_certificate_valid_from.DeviceType4friendlyCertificate_ValidFrom(
                        ms = 1552301131000, 
                        tz = 'UTC', ), 
                    valid_until = dscc.models.device_type4friendly_certificate_valid_until.DeviceType4friendlyCertificate_ValidUntil(
                        ms = 1615416331000, 
                        tz = 'UTC', ), 
                    issued_to = 'example.hpe.com', 
                    issuer = 'CA', ),
                generation = 1627540911681,
                mail_host_domain = 'hpe.com',
                mail_host_server = 'example.hpe.com',
                port = 25,
                request_uri = '/api/v1/storage-systems/device-type1/7CE751P312/mailsettings',
                sender_email_id = 'someone@maildomain.com',
                type = 'mail-settings',
                username = 'username'
            )
        else:
            return Mailsettings(
        )
        """

    def testMailsettings(self):
        """Test Mailsettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
