# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.fleet_volume_set_details import FleetVolumeSetDetails

class TestFleetVolumeSetDetails(unittest.TestCase):
    """FleetVolumeSetDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FleetVolumeSetDetails:
        """Test FleetVolumeSetDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FleetVolumeSetDetails`
        """
        model = FleetVolumeSetDetails()
        if include_optional:
            return FleetVolumeSetDetails(
                app_type = 'Oracle Database',
                application = '',
                associated_links = [
                    dscc.models.associated_links_inner.AssociatedLinks_inner(
                        resource_uri = '', 
                        type = '', )
                    ],
                common_resource_attributes = dscc.models.common_resource_attributesfleet.commonResourceAttributesfleet(
                    cloud_state = 'CONNECTED', ),
                customer_id = 'string',
                generation = 0,
                id = '4c74ec5c-ecec-4483-9506-3fb5dc45b5d0',
                name = 'snap11',
                product_family = 'deviceType1',
                resource_uri = '/v1/storage-systems/volume-sets',
                system_id = '7CE751P312',
                type = 'string'
            )
        else:
            return FleetVolumeSetDetails(
        )
        """

    def testFleetVolumeSetDetails(self):
        """Test FleetVolumeSetDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
