# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.perf_stats import PerfStats

class TestPerfStats(unittest.TestCase):
    """PerfStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PerfStats:
        """Test PerfStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PerfStats`
        """
        model = PerfStats()
        if include_optional:
            return PerfStats(
                cache_percentage = dscc.models.perf_data.perfData(
                    avg_of1day = 33.65, 
                    avg_of1hour = 40.4, 
                    avg_of8hours = 50.98, 
                    avg_oflatest = 3.4, ),
                common_resource_attributes = dscc.models.primera_common_resource_attributes.primeraCommonResourceAttributes(
                    cloud_state = 'CONNECTED', ),
                cpu_percentage = dscc.models.perf_data.perfData(
                    avg_of1day = 33.65, 
                    avg_of1hour = 40.4, 
                    avg_of8hours = 50.98, 
                    avg_oflatest = 3.4, ),
                customer_id = 'string',
                request_uri = 'v1/storage-systems/device-type1/7CE751P312/component-performance-statistics'
            )
        else:
            return PerfStats(
        )
        """

    def testPerfStats(self):
        """Test PerfStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
