# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.volume_set_put import VolumeSetPut

class TestVolumeSetPut(unittest.TestCase):
    """VolumeSetPut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VolumeSetPut:
        """Test VolumeSetPut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VolumeSetPut`
        """
        model = VolumeSetPut()
        if include_optional:
            return VolumeSetPut(
                add_members = ["vol1","vol2"],
                app_set_business_unit = 'HPE',
                app_set_comments = 'Edit appset',
                app_set_importance = 'MEDIUM',
                app_set_name = 'Appset_134',
                app_set_type = 'ORACLE_LOG',
                custom_app_type = 'CustomWorkload_123',
                edit_app_set_qos_config_input = dscc.models.edit_app_set_qos_config_input.EditAppSetQosConfigInput(
                    action = 'ADD_QOS', 
                    bandwidth_max_limit_ki_b = 100, 
                    enable = True, 
                    iops_max_limit = 1, ),
                remove_members = ["vol1","vol2"]
            )
        else:
            return VolumeSetPut(
        )
        """

    def testVolumeSetPut(self):
        """Test VolumeSetPut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
