# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.device_type4details_inner_args_inner import DeviceType4detailsInnerArgsInner

class TestDeviceType4detailsInnerArgsInner(unittest.TestCase):
    """DeviceType4detailsInnerArgsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceType4detailsInnerArgsInner:
        """Test DeviceType4detailsInnerArgsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceType4detailsInnerArgsInner`
        """
        model = DeviceType4detailsInnerArgsInner()
        if include_optional:
            return DeviceType4detailsInnerArgsInner(
                ms = 1599631885,
                tz = 'Asia/Kolkata'
            )
        else:
            return DeviceType4detailsInnerArgsInner(
        )
        """

    def testDeviceType4detailsInnerArgsInner(self):
        """Test DeviceType4detailsInnerArgsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
