# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.device_type4_witness_list import DeviceType4WitnessList

class TestDeviceType4WitnessList(unittest.TestCase):
    """DeviceType4WitnessList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceType4WitnessList:
        """Test DeviceType4WitnessList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceType4WitnessList`
        """
        model = DeviceType4WitnessList()
        if include_optional:
            return DeviceType4WitnessList(
                items = [
                    dscc.models.device_type4_witness.DeviceType4Witness()
                    ],
                page_limit = 1,
                page_offset = 1,
                request_uri = '/api/v1/storage-systems/device-type4/SGH000XWEE/system-settings/quorum-witness',
                total = 1
            )
        else:
            return DeviceType4WitnessList(
        )
        """

    def testDeviceType4WitnessList(self):
        """Test DeviceType4WitnessList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
