# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.friendly_certificate import FriendlyCertificate

class TestFriendlyCertificate(unittest.TestCase):
    """FriendlyCertificate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FriendlyCertificate:
        """Test FriendlyCertificate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FriendlyCertificate`
        """
        model = FriendlyCertificate()
        if include_optional:
            return FriendlyCertificate(
                valid_from = dscc.models.device_type4friendly_certificate_valid_from.DeviceType4friendlyCertificate_ValidFrom(
                    ms = 1552301131000, 
                    tz = 'UTC', ),
                valid_until = dscc.models.device_type4friendly_certificate_valid_until.DeviceType4friendlyCertificate_ValidUntil(
                    ms = 1615416331000, 
                    tz = 'UTC', ),
                issued_to = 'example.hpe.com',
                issuer = 'CA'
            )
        else:
            return FriendlyCertificate(
        )
        """

    def testFriendlyCertificate(self):
        """Test FriendlyCertificate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
