# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.device_type4_editv_vol_sc_input import DeviceType4EditvVolSCInput

class TestDeviceType4EditvVolSCInput(unittest.TestCase):
    """DeviceType4EditvVolSCInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceType4EditvVolSCInput:
        """Test DeviceType4EditvVolSCInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceType4EditvVolSCInput`
        """
        model = DeviceType4EditvVolSCInput()
        if include_optional:
            return DeviceType4EditvVolSCInput(
                comment = 'Storage Container is for the volume',
                growth_limit_mi_b = 20,
                growth_size_mi_b = 10,
                growth_warn_mi_b = 18,
                name = '<resource_name>'
            )
        else:
            return DeviceType4EditvVolSCInput(
        )
        """

    def testDeviceType4EditvVolSCInput(self):
        """Test DeviceType4EditvVolSCInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
