# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.device_type4_application_set_capacity_stats_capacity_summary import DeviceType4ApplicationSetCapacityStatsCapacitySummary

class TestDeviceType4ApplicationSetCapacityStatsCapacitySummary(unittest.TestCase):
    """DeviceType4ApplicationSetCapacityStatsCapacitySummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceType4ApplicationSetCapacityStatsCapacitySummary:
        """Test DeviceType4ApplicationSetCapacityStatsCapacitySummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceType4ApplicationSetCapacityStatsCapacitySummary`
        """
        model = DeviceType4ApplicationSetCapacityStatsCapacitySummary()
        if include_optional:
            return DeviceType4ApplicationSetCapacityStatsCapacitySummary(
                free_size_mi_b = 1233920,
                size_mi_b = 595968,
                used_size_mi_b = 595968
            )
        else:
            return DeviceType4ApplicationSetCapacityStatsCapacitySummary(
        )
        """

    def testDeviceType4ApplicationSetCapacityStatsCapacitySummary(self):
        """Test DeviceType4ApplicationSetCapacityStatsCapacitySummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
