# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.device_type4_createv_vol_sc_input import DeviceType4CreatevVolSCInput

class TestDeviceType4CreatevVolSCInput(unittest.TestCase):
    """DeviceType4CreatevVolSCInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceType4CreatevVolSCInput:
        """Test DeviceType4CreatevVolSCInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceType4CreatevVolSCInput`
        """
        model = DeviceType4CreatevVolSCInput()
        if include_optional:
            return DeviceType4CreatevVolSCInput(
                domain = 'domain',
                host_ids = ["id","id"],
                host_set_ids = ["id","id"],
                name = '<resource_name>',
                sc_type = 'SCSI'
            )
        else:
            return DeviceType4CreatevVolSCInput(
                name = '<resource_name>',
        )
        """

    def testDeviceType4CreatevVolSCInput(self):
        """Test DeviceType4CreatevVolSCInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
