# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.device_type4_enclosure_card_detailed_fields_enclosure_card_fan import DeviceType4EnclosureCardDetailedFieldsEnclosureCardFan

class TestDeviceType4EnclosureCardDetailedFieldsEnclosureCardFan(unittest.TestCase):
    """DeviceType4EnclosureCardDetailedFieldsEnclosureCardFan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceType4EnclosureCardDetailedFieldsEnclosureCardFan:
        """Test DeviceType4EnclosureCardDetailedFieldsEnclosureCardFan
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceType4EnclosureCardDetailedFieldsEnclosureCardFan`
        """
        model = DeviceType4EnclosureCardDetailedFieldsEnclosureCardFan()
        if include_optional:
            return DeviceType4EnclosureCardDetailedFieldsEnclosureCardFan(
                items = [
                    dscc.models.device_type4enclosure_card_fan_details.DeviceType4enclosureCardFanDetails(
                        common_resource_attributes = dscc.models.common_resource_attributes.commonResourceAttributes(
                            cloud_state = 'CONNECTED', ), 
                        customer_id = 'string', 
                        displayname = '', 
                        domain = '', 
                        element_status_code = '', 
                        enclosure_card_fan_id = 0, 
                        enclosure_card_id = 0, 
                        enclosure_card_uid = '9c3c4f29a82fd8d632ff379116fa0b8f', 
                        enclosure_id = 0, 
                        enclosure_name = '', 
                        enclosure_type = 'ENCLOSURE_DCS8', 
                        enclosure_uid = '9c3c4f29a82fd8d632ff379116fa0b8f', 
                        fail_indicator = False, 
                        fan_id = '7CE751P312', 
                        fan_uid = '7CE751P312', 
                        generation = 0, 
                        id = '9c3c4f29a82fd8d632ff379116fa0b8f', 
                        manufacturing = dscc.models.device_type4_manufacturing_single.DeviceType4ManufacturingSingle(
                            assembly_rev = '002*', 
                            check_sum = '--', 
                            hpe_model_name = 'HPE 3PAR 600 2S Node', 
                            manufacturer = 'XYRATEX', 
                            model = '0974244-06', 
                            saleable_part_number = '0974244-06', 
                            saleable_serial_number = '4UW0002941', 
                            serial_number = 'PMW0974244G4T88', 
                            spare_part_number = 'P04031-001', ), 
                        name = 'SASB', 
                        speed = '', 
                        state = dscc.models.device_type4_state.DeviceType4State(
                            detailed = [
                                ''
                                ], 
                            overall = 'STATE_NORMAL', ), 
                        system_id = '7CE751P312', 
                        type = 'string', )
                    ],
                page_limit = 1,
                page_offset = 1,
                total = 1
            )
        else:
            return DeviceType4EnclosureCardDetailedFieldsEnclosureCardFan(
        )
        """

    def testDeviceType4EnclosureCardDetailedFieldsEnclosureCardFan(self):
        """Test DeviceType4EnclosureCardDetailedFieldsEnclosureCardFan"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
