# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.nimble_test_witness_response import NimbleTestWitnessResponse

class TestNimbleTestWitnessResponse(unittest.TestCase):
    """NimbleTestWitnessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NimbleTestWitnessResponse:
        """Test NimbleTestWitnessResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NimbleTestWitnessResponse`
        """
        model = NimbleTestWitnessResponse()
        if include_optional:
            return NimbleTestWitnessResponse(
                response = [
                    dscc.models.witness_test_response.WitnessTestResponse(
                        array_name = 'Nimble Array056', 
                        role = 'leader', 
                        witness_connectivity_message = 'example reachability message', 
                        witness_connectivity_state = 'reachable', )
                    ]
            )
        else:
            return NimbleTestWitnessResponse(
                response = [
                    dscc.models.witness_test_response.WitnessTestResponse(
                        array_name = 'Nimble Array056', 
                        role = 'leader', 
                        witness_connectivity_message = 'example reachability message', 
                        witness_connectivity_state = 'reachable', )
                    ],
        )
        """

    def testNimbleTestWitnessResponse(self):
        """Test NimbleTestWitnessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
