# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.device_type4_edit_replication_partner_input import DeviceType4EditReplicationPartnerInput

class TestDeviceType4EditReplicationPartnerInput(unittest.TestCase):
    """DeviceType4EditReplicationPartnerInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceType4EditReplicationPartnerInput:
        """Test DeviceType4EditReplicationPartnerInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceType4EditReplicationPartnerInput`
        """
        model = DeviceType4EditReplicationPartnerInput()
        if include_optional:
            return DeviceType4EditReplicationPartnerInput(
                add_rc_links = dscc.models.device_type4_add_remote_copy_links.DeviceType4AddRemoteCopyLinks(
                    replication_partner_system_id = '7CE816P0SR', 
                    source = [
                        dscc.models.device_type4_create_remote_copy_link_input.DeviceType4CreateRemoteCopyLinkInput(
                            address = '10.100.65.128', 
                            port_pos = dscc.models.create_remote_copy_link_input_port_pos.CreateRemoteCopyLinkInput_portPos(
                                node = 0, 
                                port = 3, 
                                slot = 1, ), 
                            target_name = 'Sample_RCTarget', 
                            type = 1, )
                        ], 
                    target = [
                        dscc.models.device_type4_create_remote_copy_link_input.DeviceType4CreateRemoteCopyLinkInput(
                            address = '10.100.65.128', 
                            port_pos = dscc.models.create_remote_copy_link_input_port_pos.CreateRemoteCopyLinkInput_portPos(
                                node = 0, 
                                port = 3, 
                                slot = 1, ), 
                            target_name = 'Sample_RCTarget', 
                            type = 1, )
                        ], ),
                remove_rc_links = dscc.models.device_type4_remove_remote_copy_links_input.DeviceType4RemoveRemoteCopyLinksInput(
                    replication_partner_system_id = '7CE816P0SR', 
                    source = [
                        dscc.models.device_type4_rc_link_id.DeviceType4RCLinkId(
                            rc_link_id = 'afb4961e47212e5bc88dd35db5be5c82', )
                        ], 
                    target = [
                        dscc.models.device_type4_rc_link_id.DeviceType4RCLinkId(
                            rc_link_id = 'afb4961e47212e5bc88dd35db5be5c82', )
                        ], )
            )
        else:
            return DeviceType4EditReplicationPartnerInput(
        )
        """

    def testDeviceType4EditReplicationPartnerInput(self):
        """Test DeviceType4EditReplicationPartnerInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
