# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dscc.models.nimble_arrays_list import NimbleArraysList

class TestNimbleArraysList(unittest.TestCase):
    """NimbleArraysList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NimbleArraysList:
        """Test NimbleArraysList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NimbleArraysList`
        """
        model = NimbleArraysList()
        if include_optional:
            return NimbleArraysList(
                array_name = 'myobject-5',
                array_id = '2a0df0fe6f7dc7bb16000000000000000000004817',
                ctrlr_a_fc_config = dscc.models.nimble_controller_config.NimbleControllerConfig(),
                ctrlr_b_fc_config = dscc.models.nimble_controller_config.NimbleControllerConfig(),
                id = '2a0df0fe6f7dc7bb16000000000000000000004817',
                name = 'myobject-5'
            )
        else:
            return NimbleArraysList(
        )
        """

    def testNimbleArraysList(self):
        """Test NimbleArraysList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
