# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from dscc.models.create_remote_copy_link_input import CreateRemoteCopyLinkInput
from typing import Optional, Set
from typing_extensions import Self

class AddRemoteCopyLinks(BaseModel):
    """
    Request body for adding remote copy links
    """ # noqa: E501
    replication_partner_system_id: StrictStr = Field(description="SystemId of target replication partner", alias="replicationPartnerSystemId")
    source: List[CreateRemoteCopyLinkInput] = Field(description="List of remote copy links to be added to source replication partner")
    target: List[CreateRemoteCopyLinkInput] = Field(description="List of remote copy links to be added to target replication partner")
    __properties: ClassVar[List[str]] = ["replicationPartnerSystemId", "source", "target"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddRemoteCopyLinks from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in source (list)
        _items = []
        if self.source:
            for _item in self.source:
                if _item:
                    _items.append(_item.to_dict())
            _dict['source'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in target (list)
        _items = []
        if self.target:
            for _item in self.target:
                if _item:
                    _items.append(_item.to_dict())
            _dict['target'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddRemoteCopyLinks from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "replicationPartnerSystemId": obj.get("replicationPartnerSystemId"),
            "source": [CreateRemoteCopyLinkInput.from_dict(_item) for _item in obj["source"]] if obj.get("source") is not None else None,
            "target": [CreateRemoteCopyLinkInput.from_dict(_item) for _item in obj["target"]] if obj.get("target") is not None else None
        })
        return _obj


