# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DeviceType4systemSettingsDetailsInstallationsites(BaseModel):
    """
    DeviceType4systemSettingsDetailsInstallationsites
    """ # noqa: E501
    city: Optional[StrictStr] = Field(default=None, description="City of the installation site")
    company: Optional[StrictStr] = Field(default=None, description="Company name of the installation site")
    country: Optional[StrictStr] = Field(default=None, description="Country of the installation site")
    hpe_passport_id: Optional[StrictStr] = Field(default=None, description="HPE passport ID", alias="hpePassportId")
    hpe_password: Optional[StrictStr] = Field(default=None, description="Password of an HPE passport ID", alias="hpePassword")
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier of the installation site")
    postal_code: Optional[StrictStr] = Field(default=None, description="Postal code of the installation site", alias="postalCode")
    set_system_location: Optional[StrictBool] = Field(default=None, description="Apply system location to the system descriptor property", alias="setSystemLocation")
    state: Optional[StrictStr] = Field(default=None, description="State of the installation site")
    street_address: Optional[StrictStr] = Field(default=None, description="Street address of the installation site", alias="streetAddress")
    support_provider: Optional[StrictStr] = Field(default=None, description="Support provider of the installation site", alias="supportProvider")
    system_id: Optional[StrictStr] = Field(default=None, description="SystemId/serialNumber of the array.", alias="systemId")
    __properties: ClassVar[List[str]] = ["city", "company", "country", "hpePassportId", "hpePassword", "id", "postalCode", "setSystemLocation", "state", "streetAddress", "supportProvider", "systemId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeviceType4systemSettingsDetailsInstallationsites from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        # set to None if company (nullable) is None
        # and model_fields_set contains the field
        if self.company is None and "company" in self.model_fields_set:
            _dict['company'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if hpe_passport_id (nullable) is None
        # and model_fields_set contains the field
        if self.hpe_passport_id is None and "hpe_passport_id" in self.model_fields_set:
            _dict['hpePassportId'] = None

        # set to None if hpe_password (nullable) is None
        # and model_fields_set contains the field
        if self.hpe_password is None and "hpe_password" in self.model_fields_set:
            _dict['hpePassword'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if postal_code (nullable) is None
        # and model_fields_set contains the field
        if self.postal_code is None and "postal_code" in self.model_fields_set:
            _dict['postalCode'] = None

        # set to None if set_system_location (nullable) is None
        # and model_fields_set contains the field
        if self.set_system_location is None and "set_system_location" in self.model_fields_set:
            _dict['setSystemLocation'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        # set to None if street_address (nullable) is None
        # and model_fields_set contains the field
        if self.street_address is None and "street_address" in self.model_fields_set:
            _dict['streetAddress'] = None

        # set to None if support_provider (nullable) is None
        # and model_fields_set contains the field
        if self.support_provider is None and "support_provider" in self.model_fields_set:
            _dict['supportProvider'] = None

        # set to None if system_id (nullable) is None
        # and model_fields_set contains the field
        if self.system_id is None and "system_id" in self.model_fields_set:
            _dict['systemId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeviceType4systemSettingsDetailsInstallationsites from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "city": obj.get("city"),
            "company": obj.get("company"),
            "country": obj.get("country"),
            "hpePassportId": obj.get("hpePassportId"),
            "hpePassword": obj.get("hpePassword"),
            "id": obj.get("id"),
            "postalCode": obj.get("postalCode"),
            "setSystemLocation": obj.get("setSystemLocation"),
            "state": obj.get("state"),
            "streetAddress": obj.get("streetAddress"),
            "supportProvider": obj.get("supportProvider"),
            "systemId": obj.get("systemId")
        })
        return _obj


