# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from dscc.models.device_type4_manufacturing_single import DeviceType4ManufacturingSingle
from dscc.models.device_type4_state import DeviceType4State
from dscc.models.device_type4dc4data_single import DeviceType4dc4dataSingle
from dscc.models.device_type4enclosure_type_single import DeviceType4enclosureTypeSingle
from typing import Optional, Set
from typing_extensions import Self

class DeviceType4enclosureSledLists(BaseModel):
    """
    DeviceType4enclosureSledLists
    """ # noqa: E501
    customer_id: Optional[StrictStr] = Field(default=None, description="customerId", alias="customerId")
    dc4data: Optional[DeviceType4dc4dataSingle] = None
    disk_count: Optional[StrictInt] = Field(default=None, description="Number of disks present", alias="diskCount")
    displayname: Optional[StrictStr] = Field(default=None, description="Enclosure Display name")
    domain: Optional[StrictStr] = Field(default=None, description="Domain that the resource belongs to")
    element_status_code: Optional[StrictStr] = Field(default=None, description="Enclosure status code", alias="elementStatusCode")
    enclosure_id: Optional[StrictInt] = Field(default=None, alias="enclosureId")
    enclosure_name: Optional[StrictStr] = Field(default=None, description="Name of the enclosure", alias="enclosureName")
    enclosure_type: Optional[DeviceType4enclosureTypeSingle] = Field(default=None, alias="enclosureType")
    enclosure_uid: Optional[StrictStr] = Field(default=None, description="Parent UID of the resource.", alias="enclosureUid")
    fail_indicator: Optional[StrictBool] = Field(default=None, alias="failIndicator")
    generation: Optional[StrictInt] = Field(default=None, description="generation")
    id: Optional[StrictStr] = Field(default=None, description="Unique Identifier of the resource.")
    locate_enabled: Optional[StrictBool] = Field(default=None, description="Indicates if the locate beacon is enabled or not", alias="locateEnabled")
    manufacturing: Optional[DeviceType4ManufacturingSingle] = None
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Name of the resource.")
    ok_indicator: Optional[StrictBool] = Field(default=None, alias="okIndicator")
    port_bypass_a: Optional[StrictBool] = Field(default=None, alias="portBypassA")
    port_bypass_b: Optional[StrictBool] = Field(default=None, alias="portBypassB")
    power: Optional[StrictBool] = None
    pred_fail_indicator: Optional[StrictBool] = Field(default=None, alias="predFailIndicator")
    protocol: Optional[StrictStr] = None
    resource_uri: Optional[StrictStr] = Field(default=None, description="resourceUri for detailed enclosure object", alias="resourceUri")
    safe_to_remove: Optional[StrictBool] = Field(default=None, alias="safeToRemove")
    sled_id: Optional[StrictInt] = Field(default=None, description="Numeric ID of the resource", alias="sledId")
    state_loop_a: Optional[DeviceType4State] = Field(default=None, alias="stateLoopA")
    state_loop_b: Optional[DeviceType4State] = Field(default=None, alias="stateLoopB")
    system_id: Optional[StrictStr] = Field(default=None, description="SystemUid/Serial Number  of the array.", alias="systemId")
    temperature: Optional[StrictInt] = None
    type: Optional[StrictStr] = Field(default=None, description="type")
    wwn: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["customerId", "dc4data", "diskCount", "displayname", "domain", "elementStatusCode", "enclosureId", "enclosureName", "enclosureType", "enclosureUid", "failIndicator", "generation", "id", "locateEnabled", "manufacturing", "name", "okIndicator", "portBypassA", "portBypassB", "power", "predFailIndicator", "protocol", "resourceUri", "safeToRemove", "sledId", "stateLoopA", "stateLoopB", "systemId", "temperature", "type", "wwn"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeviceType4enclosureSledLists from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of dc4data
        if self.dc4data:
            _dict['dc4data'] = self.dc4data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of manufacturing
        if self.manufacturing:
            _dict['manufacturing'] = self.manufacturing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of state_loop_a
        if self.state_loop_a:
            _dict['stateLoopA'] = self.state_loop_a.to_dict()
        # override the default output from pydantic by calling `to_dict()` of state_loop_b
        if self.state_loop_b:
            _dict['stateLoopB'] = self.state_loop_b.to_dict()
        # set to None if customer_id (nullable) is None
        # and model_fields_set contains the field
        if self.customer_id is None and "customer_id" in self.model_fields_set:
            _dict['customerId'] = None

        # set to None if dc4data (nullable) is None
        # and model_fields_set contains the field
        if self.dc4data is None and "dc4data" in self.model_fields_set:
            _dict['dc4data'] = None

        # set to None if disk_count (nullable) is None
        # and model_fields_set contains the field
        if self.disk_count is None and "disk_count" in self.model_fields_set:
            _dict['diskCount'] = None

        # set to None if displayname (nullable) is None
        # and model_fields_set contains the field
        if self.displayname is None and "displayname" in self.model_fields_set:
            _dict['displayname'] = None

        # set to None if domain (nullable) is None
        # and model_fields_set contains the field
        if self.domain is None and "domain" in self.model_fields_set:
            _dict['domain'] = None

        # set to None if element_status_code (nullable) is None
        # and model_fields_set contains the field
        if self.element_status_code is None and "element_status_code" in self.model_fields_set:
            _dict['elementStatusCode'] = None

        # set to None if enclosure_name (nullable) is None
        # and model_fields_set contains the field
        if self.enclosure_name is None and "enclosure_name" in self.model_fields_set:
            _dict['enclosureName'] = None

        # set to None if enclosure_uid (nullable) is None
        # and model_fields_set contains the field
        if self.enclosure_uid is None and "enclosure_uid" in self.model_fields_set:
            _dict['enclosureUid'] = None

        # set to None if fail_indicator (nullable) is None
        # and model_fields_set contains the field
        if self.fail_indicator is None and "fail_indicator" in self.model_fields_set:
            _dict['failIndicator'] = None

        # set to None if generation (nullable) is None
        # and model_fields_set contains the field
        if self.generation is None and "generation" in self.model_fields_set:
            _dict['generation'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if locate_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.locate_enabled is None and "locate_enabled" in self.model_fields_set:
            _dict['locateEnabled'] = None

        # set to None if manufacturing (nullable) is None
        # and model_fields_set contains the field
        if self.manufacturing is None and "manufacturing" in self.model_fields_set:
            _dict['manufacturing'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if ok_indicator (nullable) is None
        # and model_fields_set contains the field
        if self.ok_indicator is None and "ok_indicator" in self.model_fields_set:
            _dict['okIndicator'] = None

        # set to None if port_bypass_a (nullable) is None
        # and model_fields_set contains the field
        if self.port_bypass_a is None and "port_bypass_a" in self.model_fields_set:
            _dict['portBypassA'] = None

        # set to None if port_bypass_b (nullable) is None
        # and model_fields_set contains the field
        if self.port_bypass_b is None and "port_bypass_b" in self.model_fields_set:
            _dict['portBypassB'] = None

        # set to None if power (nullable) is None
        # and model_fields_set contains the field
        if self.power is None and "power" in self.model_fields_set:
            _dict['power'] = None

        # set to None if pred_fail_indicator (nullable) is None
        # and model_fields_set contains the field
        if self.pred_fail_indicator is None and "pred_fail_indicator" in self.model_fields_set:
            _dict['predFailIndicator'] = None

        # set to None if protocol (nullable) is None
        # and model_fields_set contains the field
        if self.protocol is None and "protocol" in self.model_fields_set:
            _dict['protocol'] = None

        # set to None if resource_uri (nullable) is None
        # and model_fields_set contains the field
        if self.resource_uri is None and "resource_uri" in self.model_fields_set:
            _dict['resourceUri'] = None

        # set to None if safe_to_remove (nullable) is None
        # and model_fields_set contains the field
        if self.safe_to_remove is None and "safe_to_remove" in self.model_fields_set:
            _dict['safeToRemove'] = None

        # set to None if sled_id (nullable) is None
        # and model_fields_set contains the field
        if self.sled_id is None and "sled_id" in self.model_fields_set:
            _dict['sledId'] = None

        # set to None if state_loop_a (nullable) is None
        # and model_fields_set contains the field
        if self.state_loop_a is None and "state_loop_a" in self.model_fields_set:
            _dict['stateLoopA'] = None

        # set to None if state_loop_b (nullable) is None
        # and model_fields_set contains the field
        if self.state_loop_b is None and "state_loop_b" in self.model_fields_set:
            _dict['stateLoopB'] = None

        # set to None if system_id (nullable) is None
        # and model_fields_set contains the field
        if self.system_id is None and "system_id" in self.model_fields_set:
            _dict['systemId'] = None

        # set to None if temperature (nullable) is None
        # and model_fields_set contains the field
        if self.temperature is None and "temperature" in self.model_fields_set:
            _dict['temperature'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if wwn (nullable) is None
        # and model_fields_set contains the field
        if self.wwn is None and "wwn" in self.model_fields_set:
            _dict['wwn'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeviceType4enclosureSledLists from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "customerId": obj.get("customerId"),
            "dc4data": DeviceType4dc4dataSingle.from_dict(obj["dc4data"]) if obj.get("dc4data") is not None else None,
            "diskCount": obj.get("diskCount"),
            "displayname": obj.get("displayname"),
            "domain": obj.get("domain"),
            "elementStatusCode": obj.get("elementStatusCode"),
            "enclosureId": obj.get("enclosureId"),
            "enclosureName": obj.get("enclosureName"),
            "enclosureType": obj.get("enclosureType"),
            "enclosureUid": obj.get("enclosureUid"),
            "failIndicator": obj.get("failIndicator"),
            "generation": obj.get("generation"),
            "id": obj.get("id"),
            "locateEnabled": obj.get("locateEnabled"),
            "manufacturing": DeviceType4ManufacturingSingle.from_dict(obj["manufacturing"]) if obj.get("manufacturing") is not None else None,
            "name": obj.get("name"),
            "okIndicator": obj.get("okIndicator"),
            "portBypassA": obj.get("portBypassA"),
            "portBypassB": obj.get("portBypassB"),
            "power": obj.get("power"),
            "predFailIndicator": obj.get("predFailIndicator"),
            "protocol": obj.get("protocol"),
            "resourceUri": obj.get("resourceUri"),
            "safeToRemove": obj.get("safeToRemove"),
            "sledId": obj.get("sledId"),
            "stateLoopA": DeviceType4State.from_dict(obj["stateLoopA"]) if obj.get("stateLoopA") is not None else None,
            "stateLoopB": DeviceType4State.from_dict(obj["stateLoopB"]) if obj.get("stateLoopB") is not None else None,
            "systemId": obj.get("systemId"),
            "temperature": obj.get("temperature"),
            "type": obj.get("type"),
            "wwn": obj.get("wwn")
        })
        return _obj


