# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dscc.models.associated_links_inner import AssociatedLinksInner
from dscc.models.nimble_common_resource_attributes import NimbleCommonResourceAttributes
from dscc.models.nimble_perf_policy_summary import NimblePerfPolicySummary
from dscc.models.nimble_volume_summary import NimbleVolumeSummary
from typing import Optional, Set
from typing_extensions import Self

class NimbleSpaceDomainDetails(BaseModel):
    """
    NimbleSpaceDomainDetails
    """ # noqa: E501
    associated_links: Optional[List[Optional[AssociatedLinksInner]]] = Field(default=None, description="Associated Links Details")
    common_resource_attributes: Optional[NimbleCommonResourceAttributes] = Field(default=None, alias="commonResourceAttributes")
    console_uri: Optional[StrictStr] = Field(default=None, description="consoleUri for detailed storage object", alias="consoleUri")
    customer_id: Optional[StrictStr] = Field(default=None, description="customerId", alias="customerId")
    deduped_volume_count: Optional[StrictInt] = Field(default=None, description="Number of deduplicated volumes belonging to the space domain.")
    generation: Optional[StrictInt] = Field(default=None, description="generation")
    perf_policy_names: Optional[List[Optional[NimblePerfPolicySummary]]] = Field(default=None, description="Name of the performance policies associated with the space domain.")
    resource_uri: Optional[StrictStr] = Field(default=None, description="Link to the object URI", alias="resourceUri")
    sample_rate: Optional[StrictInt] = Field(default=None, description="Sample rate value.")
    type: Optional[StrictStr] = Field(default=None, description="type")
    volume_count: Optional[StrictInt] = Field(default=None, description="Number of volumes belonging to the space domain.")
    volumes: Optional[List[Optional[NimbleVolumeSummary]]] = Field(default=None, description="Volumes belonging to the space domain.")
    __properties: ClassVar[List[str]] = ["associated_links", "commonResourceAttributes", "consoleUri", "customerId", "deduped_volume_count", "generation", "perf_policy_names", "resourceUri", "sample_rate", "type", "volume_count", "volumes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NimbleSpaceDomainDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in associated_links (list)
        _items = []
        if self.associated_links:
            for _item in self.associated_links:
                if _item:
                    _items.append(_item.to_dict())
            _dict['associated_links'] = _items
        # override the default output from pydantic by calling `to_dict()` of common_resource_attributes
        if self.common_resource_attributes:
            _dict['commonResourceAttributes'] = self.common_resource_attributes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in perf_policy_names (list)
        _items = []
        if self.perf_policy_names:
            for _item in self.perf_policy_names:
                if _item:
                    _items.append(_item.to_dict())
            _dict['perf_policy_names'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in volumes (list)
        _items = []
        if self.volumes:
            for _item in self.volumes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['volumes'] = _items
        # set to None if common_resource_attributes (nullable) is None
        # and model_fields_set contains the field
        if self.common_resource_attributes is None and "common_resource_attributes" in self.model_fields_set:
            _dict['commonResourceAttributes'] = None

        # set to None if console_uri (nullable) is None
        # and model_fields_set contains the field
        if self.console_uri is None and "console_uri" in self.model_fields_set:
            _dict['consoleUri'] = None

        # set to None if customer_id (nullable) is None
        # and model_fields_set contains the field
        if self.customer_id is None and "customer_id" in self.model_fields_set:
            _dict['customerId'] = None

        # set to None if deduped_volume_count (nullable) is None
        # and model_fields_set contains the field
        if self.deduped_volume_count is None and "deduped_volume_count" in self.model_fields_set:
            _dict['deduped_volume_count'] = None

        # set to None if generation (nullable) is None
        # and model_fields_set contains the field
        if self.generation is None and "generation" in self.model_fields_set:
            _dict['generation'] = None

        # set to None if perf_policy_names (nullable) is None
        # and model_fields_set contains the field
        if self.perf_policy_names is None and "perf_policy_names" in self.model_fields_set:
            _dict['perf_policy_names'] = None

        # set to None if resource_uri (nullable) is None
        # and model_fields_set contains the field
        if self.resource_uri is None and "resource_uri" in self.model_fields_set:
            _dict['resourceUri'] = None

        # set to None if sample_rate (nullable) is None
        # and model_fields_set contains the field
        if self.sample_rate is None and "sample_rate" in self.model_fields_set:
            _dict['sample_rate'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if volume_count (nullable) is None
        # and model_fields_set contains the field
        if self.volume_count is None and "volume_count" in self.model_fields_set:
            _dict['volume_count'] = None

        # set to None if volumes (nullable) is None
        # and model_fields_set contains the field
        if self.volumes is None and "volumes" in self.model_fields_set:
            _dict['volumes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NimbleSpaceDomainDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "associated_links": [AssociatedLinksInner.from_dict(_item) for _item in obj["associated_links"]] if obj.get("associated_links") is not None else None,
            "commonResourceAttributes": NimbleCommonResourceAttributes.from_dict(obj["commonResourceAttributes"]) if obj.get("commonResourceAttributes") is not None else None,
            "consoleUri": obj.get("consoleUri"),
            "customerId": obj.get("customerId"),
            "deduped_volume_count": obj.get("deduped_volume_count"),
            "generation": obj.get("generation"),
            "perf_policy_names": [NimblePerfPolicySummary.from_dict(_item) for _item in obj["perf_policy_names"]] if obj.get("perf_policy_names") is not None else None,
            "resourceUri": obj.get("resourceUri"),
            "sample_rate": obj.get("sample_rate"),
            "type": obj.get("type"),
            "volume_count": obj.get("volume_count"),
            "volumes": [NimbleVolumeSummary.from_dict(_item) for _item in obj["volumes"]] if obj.get("volumes") is not None else None
        })
        return _obj


