# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dscc.models.associated_links_inner import AssociatedLinksInner
from dscc.models.nimble_common_resource_attributes import NimbleCommonResourceAttributes
from dscc.models.nimble_ns_schedule import NimbleNsSchedule
from typing import Optional, Set
from typing_extensions import Self

class NimbleProtectionTemplateDetailsWithRequestUri(BaseModel):
    """
    NimbleProtectionTemplateDetailsWithRequestUri
    """ # noqa: E501
    request_uri: Optional[StrictStr] = Field(default=None, description="requestUri for detailed protection-templates object", alias="requestUri")
    agent_hostname: Optional[StrictStr] = Field(default=None, description="Generic Backup agent hostname. Custom port number can be specified with agent hostname using \\\\\":\\\\\".")
    app_cluster_name: Optional[StrictStr] = Field(default=None, description="If the application is running within a Windows cluster environment then this is the cluster name.")
    app_id: Optional[StrictStr] = Field(default=None, description="Application ID running on the server. Application ID can only be specified if application synchronization is VSS.  Possible values:'exchange_dag', 'sql2012', 'sql2014', 'inval', 'sql2005', 'sql2016', 'exchange', 'sql2017', 'sql2018', 'hyperv'.")
    app_server: Optional[StrictStr] = Field(default=None, description="Application server hostname.")
    app_service_name: Optional[StrictStr] = Field(default=None, description="If the application is running within a Windows cluster environment then this is the instance name of the service running within the cluster environment.")
    app_sync: Optional[StrictStr] = Field(default=None, description="Application synchronization ({none|vss|vmware|generic}). Possible values:'vss', 'vmware', 'none', 'generic'.")
    creation_time: Optional[StrictInt] = Field(default=None, description="Time when this protection template was created.")
    id: Optional[StrictStr] = Field(default=None, description="Identifier for protection template.")
    last_modified: Optional[StrictInt] = Field(default=None, description="Time when this protection template was last modified.")
    name: Optional[StrictStr] = Field(default=None, description="Fully qualified name of protection template.")
    vcenter_hostname: Optional[StrictStr] = Field(default=None, description="VMware vCenter hostname. Custom port number can be specified with vCenter hostname.")
    agent_username: Optional[StrictStr] = Field(default=None, description="Generic Backup agent username.")
    associated_links: Optional[List[Optional[AssociatedLinksInner]]] = Field(default=None, description="Associated Links Details")
    common_resource_attributes: Optional[NimbleCommonResourceAttributes] = Field(default=None, alias="commonResourceAttributes")
    console_uri: Optional[StrictStr] = Field(default=None, description="consoleUri for detailed storage object", alias="consoleUri")
    customer_id: Optional[StrictStr] = Field(default=None, description="customerId", alias="customerId")
    description: Optional[StrictStr] = Field(default=None, description="Text description of protection template.")
    full_name: Optional[StrictStr] = Field(default=None, description="Fully qualified name of protection template.")
    generation: Optional[StrictInt] = Field(default=None, description="generation")
    repl_priority: Optional[StrictStr] = Field(default=None, description="Replication priority for the protection template with the following choices: {normal | high}. Possible values:'normal', 'high'.")
    resource_uri: Optional[StrictStr] = Field(default=None, description="Link to the object URI", alias="resourceUri")
    schedule_list: Optional[List[Optional[NimbleNsSchedule]]] = Field(default=None, description="List of schedules for this protection policy.")
    search_name: Optional[StrictStr] = Field(default=None, description="Name of protection template used for object search.")
    type: Optional[StrictStr] = Field(default=None, description="type")
    vcenter_username: Optional[StrictStr] = Field(default=None, description="VMware vCenter username.")
    __properties: ClassVar[List[str]] = ["agent_hostname", "app_cluster_name", "app_id", "app_server", "app_service_name", "app_sync", "creation_time", "id", "last_modified", "name", "vcenter_hostname", "agent_username", "associated_links", "commonResourceAttributes", "consoleUri", "customerId", "description", "full_name", "generation", "repl_priority", "resourceUri", "schedule_list", "search_name", "type", "vcenter_username"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NimbleProtectionTemplateDetailsWithRequestUri from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in associated_links (list)
        _items = []
        if self.associated_links:
            for _item in self.associated_links:
                if _item:
                    _items.append(_item.to_dict())
            _dict['associated_links'] = _items
        # override the default output from pydantic by calling `to_dict()` of common_resource_attributes
        if self.common_resource_attributes:
            _dict['commonResourceAttributes'] = self.common_resource_attributes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in schedule_list (list)
        _items = []
        if self.schedule_list:
            for _item in self.schedule_list:
                if _item:
                    _items.append(_item.to_dict())
            _dict['schedule_list'] = _items
        # set to None if agent_hostname (nullable) is None
        # and model_fields_set contains the field
        if self.agent_hostname is None and "agent_hostname" in self.model_fields_set:
            _dict['agent_hostname'] = None

        # set to None if app_cluster_name (nullable) is None
        # and model_fields_set contains the field
        if self.app_cluster_name is None and "app_cluster_name" in self.model_fields_set:
            _dict['app_cluster_name'] = None

        # set to None if app_id (nullable) is None
        # and model_fields_set contains the field
        if self.app_id is None and "app_id" in self.model_fields_set:
            _dict['app_id'] = None

        # set to None if app_server (nullable) is None
        # and model_fields_set contains the field
        if self.app_server is None and "app_server" in self.model_fields_set:
            _dict['app_server'] = None

        # set to None if app_service_name (nullable) is None
        # and model_fields_set contains the field
        if self.app_service_name is None and "app_service_name" in self.model_fields_set:
            _dict['app_service_name'] = None

        # set to None if app_sync (nullable) is None
        # and model_fields_set contains the field
        if self.app_sync is None and "app_sync" in self.model_fields_set:
            _dict['app_sync'] = None

        # set to None if creation_time (nullable) is None
        # and model_fields_set contains the field
        if self.creation_time is None and "creation_time" in self.model_fields_set:
            _dict['creation_time'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if last_modified (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified is None and "last_modified" in self.model_fields_set:
            _dict['last_modified'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if vcenter_hostname (nullable) is None
        # and model_fields_set contains the field
        if self.vcenter_hostname is None and "vcenter_hostname" in self.model_fields_set:
            _dict['vcenter_hostname'] = None

        # set to None if agent_username (nullable) is None
        # and model_fields_set contains the field
        if self.agent_username is None and "agent_username" in self.model_fields_set:
            _dict['agent_username'] = None

        # set to None if common_resource_attributes (nullable) is None
        # and model_fields_set contains the field
        if self.common_resource_attributes is None and "common_resource_attributes" in self.model_fields_set:
            _dict['commonResourceAttributes'] = None

        # set to None if console_uri (nullable) is None
        # and model_fields_set contains the field
        if self.console_uri is None and "console_uri" in self.model_fields_set:
            _dict['consoleUri'] = None

        # set to None if customer_id (nullable) is None
        # and model_fields_set contains the field
        if self.customer_id is None and "customer_id" in self.model_fields_set:
            _dict['customerId'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if full_name (nullable) is None
        # and model_fields_set contains the field
        if self.full_name is None and "full_name" in self.model_fields_set:
            _dict['full_name'] = None

        # set to None if generation (nullable) is None
        # and model_fields_set contains the field
        if self.generation is None and "generation" in self.model_fields_set:
            _dict['generation'] = None

        # set to None if repl_priority (nullable) is None
        # and model_fields_set contains the field
        if self.repl_priority is None and "repl_priority" in self.model_fields_set:
            _dict['repl_priority'] = None

        # set to None if resource_uri (nullable) is None
        # and model_fields_set contains the field
        if self.resource_uri is None and "resource_uri" in self.model_fields_set:
            _dict['resourceUri'] = None

        # set to None if schedule_list (nullable) is None
        # and model_fields_set contains the field
        if self.schedule_list is None and "schedule_list" in self.model_fields_set:
            _dict['schedule_list'] = None

        # set to None if search_name (nullable) is None
        # and model_fields_set contains the field
        if self.search_name is None and "search_name" in self.model_fields_set:
            _dict['search_name'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if vcenter_username (nullable) is None
        # and model_fields_set contains the field
        if self.vcenter_username is None and "vcenter_username" in self.model_fields_set:
            _dict['vcenter_username'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NimbleProtectionTemplateDetailsWithRequestUri from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_hostname": obj.get("agent_hostname"),
            "app_cluster_name": obj.get("app_cluster_name"),
            "app_id": obj.get("app_id"),
            "app_server": obj.get("app_server"),
            "app_service_name": obj.get("app_service_name"),
            "app_sync": obj.get("app_sync"),
            "creation_time": obj.get("creation_time"),
            "id": obj.get("id"),
            "last_modified": obj.get("last_modified"),
            "name": obj.get("name"),
            "vcenter_hostname": obj.get("vcenter_hostname"),
            "agent_username": obj.get("agent_username"),
            "associated_links": [AssociatedLinksInner.from_dict(_item) for _item in obj["associated_links"]] if obj.get("associated_links") is not None else None,
            "commonResourceAttributes": NimbleCommonResourceAttributes.from_dict(obj["commonResourceAttributes"]) if obj.get("commonResourceAttributes") is not None else None,
            "consoleUri": obj.get("consoleUri"),
            "customerId": obj.get("customerId"),
            "description": obj.get("description"),
            "full_name": obj.get("full_name"),
            "generation": obj.get("generation"),
            "repl_priority": obj.get("repl_priority"),
            "resourceUri": obj.get("resourceUri"),
            "schedule_list": [NimbleNsSchedule.from_dict(_item) for _item in obj["schedule_list"]] if obj.get("schedule_list") is not None else None,
            "search_name": obj.get("search_name"),
            "type": obj.get("type"),
            "vcenter_username": obj.get("vcenter_username")
        })
        return _obj


