# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class NimbleMetricSeriesData(BaseModel):
    """
    NimbleMetricSeriesData
    """ # noqa: E501
    read_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="average read metric value at particular timestamp")
    timestampms: Optional[StrictInt] = Field(default=None, description="epoch timestamp")
    total_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="total metric value at particular timestamp")
    write_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="average write metric value at particular timestamp")
    __properties: ClassVar[List[str]] = ["read_value", "timestampms", "total_value", "write_value"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NimbleMetricSeriesData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if read_value (nullable) is None
        # and model_fields_set contains the field
        if self.read_value is None and "read_value" in self.model_fields_set:
            _dict['read_value'] = None

        # set to None if timestampms (nullable) is None
        # and model_fields_set contains the field
        if self.timestampms is None and "timestampms" in self.model_fields_set:
            _dict['timestampms'] = None

        # set to None if total_value (nullable) is None
        # and model_fields_set contains the field
        if self.total_value is None and "total_value" in self.model_fields_set:
            _dict['total_value'] = None

        # set to None if write_value (nullable) is None
        # and model_fields_set contains the field
        if self.write_value is None and "write_value" in self.model_fields_set:
            _dict['write_value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NimbleMetricSeriesData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "read_value": obj.get("read_value"),
            "timestampms": obj.get("timestampms"),
            "total_value": obj.get("total_value"),
            "write_value": obj.get("write_value")
        })
        return _obj


