# coding: utf-8

"""
    Data Services Cloud Console API

    Data Services Cloud Console API

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dscc.models.associated_links_inner import AssociatedLinksInner
from dscc.models.expiration_date import ExpirationDate
from dscc.models.led import LED
from dscc.models.manufacturing_single import ManufacturingSingle
from dscc.models.primera_common_resource_attributes import PrimeraCommonResourceAttributes
from dscc.models.state import STATE
from typing import Optional, Set
from typing_extensions import Self

class NodeBatteryDetails(BaseModel):
    """
    NodeBatteryDetails
    """ # noqa: E501
    associated_links: Optional[List[Optional[AssociatedLinksInner]]] = Field(default=None, description="Associated Links Details", alias="associatedLinks")
    charge_level: Optional[StrictInt] = Field(default=None, description="Battery charge level.", alias="chargeLevel")
    common_resource_attributes: Optional[PrimeraCommonResourceAttributes] = Field(default=None, alias="commonResourceAttributes")
    console_uri: Optional[StrictStr] = Field(default=None, description="consoleUri for detailed storage object", alias="consoleUri")
    customer_id: Optional[StrictStr] = Field(default=None, description="customerId", alias="customerId")
    discharge_led: Optional[LED] = Field(default=None, alias="dischargeLED")
    displayname: Optional[StrictStr] = Field(default=None, description="Name to be used for display purposes")
    domain: Optional[StrictStr] = Field(default=None, description="Domain that the resource belongs to")
    expiration_date: Optional[ExpirationDate] = Field(default=None, alias="expirationDate")
    fault_led: Optional[LED] = Field(default=None, alias="faultLED")
    fully_charged: Optional[StrictBool] = Field(default=None, description="Indicates if battery is fully charged or not", alias="fullyCharged")
    generation: Optional[StrictInt] = Field(default=None, description="generation")
    id: Optional[StrictStr] = Field(default=None, description="Unique Identifier of the resource.")
    life: Optional[StrictInt] = Field(default=None, description="Life of the battery")
    locate_enabled: Optional[StrictBool] = Field(default=None, description="Indicates if the locate beacon is enabled or not", alias="locateEnabled")
    manufacturing: Optional[ManufacturingSingle] = None
    max_life: Optional[StrictInt] = Field(default=None, description="Maximum life of the battery", alias="maxLife")
    name: Optional[StrictStr] = Field(default=None, description="Name of the resource.")
    node_battery_id: Optional[StrictInt] = Field(default=None, description="Numeric ID of the resource", alias="nodeBatteryId")
    power_supply_id: Optional[StrictInt] = Field(default=None, description="Power supply ID for this battery.", alias="powerSupplyId")
    primary_node_id: Optional[StrictInt] = Field(default=None, description="Primary node ID.", alias="primaryNodeId")
    request_uri: Optional[StrictStr] = Field(default=None, description="requestUri for detailed node battery object", alias="requestUri")
    resource_uri: Optional[StrictStr] = Field(default=None, description="resourceUri for detailed node battery object", alias="resourceUri")
    safe_to_remove: Optional[StrictBool] = Field(default=None, description="Indicates if the component is safe to remove", alias="safeToRemove")
    secondary_node_id: Optional[StrictInt] = Field(default=None, description="Secondary node ID", alias="secondaryNodeId")
    service_led: Optional[LED] = Field(default=None, alias="serviceLED")
    state: Optional[STATE] = None
    status_led: Optional[LED] = Field(default=None, alias="statusLED")
    system_id: Optional[StrictStr] = Field(default=None, description="systemId/Serial Number  of the array.", alias="systemId")
    test_in_progress: Optional[StrictBool] = Field(default=None, description="Indicates if test is in progress or not", alias="testInProgress")
    time_to_charge: Optional[StrictInt] = Field(default=None, description="Remaining time to charge", alias="timeToCharge")
    type: Optional[StrictStr] = Field(default=None, description="type")
    __properties: ClassVar[List[str]] = ["associatedLinks", "chargeLevel", "commonResourceAttributes", "consoleUri", "customerId", "dischargeLED", "displayname", "domain", "expirationDate", "faultLED", "fullyCharged", "generation", "id", "life", "locateEnabled", "manufacturing", "maxLife", "name", "nodeBatteryId", "powerSupplyId", "primaryNodeId", "requestUri", "resourceUri", "safeToRemove", "secondaryNodeId", "serviceLED", "state", "statusLED", "systemId", "testInProgress", "timeToCharge", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodeBatteryDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in associated_links (list)
        _items = []
        if self.associated_links:
            for _item in self.associated_links:
                if _item:
                    _items.append(_item.to_dict())
            _dict['associatedLinks'] = _items
        # override the default output from pydantic by calling `to_dict()` of common_resource_attributes
        if self.common_resource_attributes:
            _dict['commonResourceAttributes'] = self.common_resource_attributes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of expiration_date
        if self.expiration_date:
            _dict['expirationDate'] = self.expiration_date.to_dict()
        # override the default output from pydantic by calling `to_dict()` of manufacturing
        if self.manufacturing:
            _dict['manufacturing'] = self.manufacturing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of state
        if self.state:
            _dict['state'] = self.state.to_dict()
        # set to None if associated_links (nullable) is None
        # and model_fields_set contains the field
        if self.associated_links is None and "associated_links" in self.model_fields_set:
            _dict['associatedLinks'] = None

        # set to None if charge_level (nullable) is None
        # and model_fields_set contains the field
        if self.charge_level is None and "charge_level" in self.model_fields_set:
            _dict['chargeLevel'] = None

        # set to None if common_resource_attributes (nullable) is None
        # and model_fields_set contains the field
        if self.common_resource_attributes is None and "common_resource_attributes" in self.model_fields_set:
            _dict['commonResourceAttributes'] = None

        # set to None if console_uri (nullable) is None
        # and model_fields_set contains the field
        if self.console_uri is None and "console_uri" in self.model_fields_set:
            _dict['consoleUri'] = None

        # set to None if customer_id (nullable) is None
        # and model_fields_set contains the field
        if self.customer_id is None and "customer_id" in self.model_fields_set:
            _dict['customerId'] = None

        # set to None if discharge_led (nullable) is None
        # and model_fields_set contains the field
        if self.discharge_led is None and "discharge_led" in self.model_fields_set:
            _dict['dischargeLED'] = None

        # set to None if displayname (nullable) is None
        # and model_fields_set contains the field
        if self.displayname is None and "displayname" in self.model_fields_set:
            _dict['displayname'] = None

        # set to None if domain (nullable) is None
        # and model_fields_set contains the field
        if self.domain is None and "domain" in self.model_fields_set:
            _dict['domain'] = None

        # set to None if expiration_date (nullable) is None
        # and model_fields_set contains the field
        if self.expiration_date is None and "expiration_date" in self.model_fields_set:
            _dict['expirationDate'] = None

        # set to None if fault_led (nullable) is None
        # and model_fields_set contains the field
        if self.fault_led is None and "fault_led" in self.model_fields_set:
            _dict['faultLED'] = None

        # set to None if fully_charged (nullable) is None
        # and model_fields_set contains the field
        if self.fully_charged is None and "fully_charged" in self.model_fields_set:
            _dict['fullyCharged'] = None

        # set to None if generation (nullable) is None
        # and model_fields_set contains the field
        if self.generation is None and "generation" in self.model_fields_set:
            _dict['generation'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if life (nullable) is None
        # and model_fields_set contains the field
        if self.life is None and "life" in self.model_fields_set:
            _dict['life'] = None

        # set to None if locate_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.locate_enabled is None and "locate_enabled" in self.model_fields_set:
            _dict['locateEnabled'] = None

        # set to None if manufacturing (nullable) is None
        # and model_fields_set contains the field
        if self.manufacturing is None and "manufacturing" in self.model_fields_set:
            _dict['manufacturing'] = None

        # set to None if max_life (nullable) is None
        # and model_fields_set contains the field
        if self.max_life is None and "max_life" in self.model_fields_set:
            _dict['maxLife'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if node_battery_id (nullable) is None
        # and model_fields_set contains the field
        if self.node_battery_id is None and "node_battery_id" in self.model_fields_set:
            _dict['nodeBatteryId'] = None

        # set to None if power_supply_id (nullable) is None
        # and model_fields_set contains the field
        if self.power_supply_id is None and "power_supply_id" in self.model_fields_set:
            _dict['powerSupplyId'] = None

        # set to None if primary_node_id (nullable) is None
        # and model_fields_set contains the field
        if self.primary_node_id is None and "primary_node_id" in self.model_fields_set:
            _dict['primaryNodeId'] = None

        # set to None if request_uri (nullable) is None
        # and model_fields_set contains the field
        if self.request_uri is None and "request_uri" in self.model_fields_set:
            _dict['requestUri'] = None

        # set to None if resource_uri (nullable) is None
        # and model_fields_set contains the field
        if self.resource_uri is None and "resource_uri" in self.model_fields_set:
            _dict['resourceUri'] = None

        # set to None if safe_to_remove (nullable) is None
        # and model_fields_set contains the field
        if self.safe_to_remove is None and "safe_to_remove" in self.model_fields_set:
            _dict['safeToRemove'] = None

        # set to None if secondary_node_id (nullable) is None
        # and model_fields_set contains the field
        if self.secondary_node_id is None and "secondary_node_id" in self.model_fields_set:
            _dict['secondaryNodeId'] = None

        # set to None if service_led (nullable) is None
        # and model_fields_set contains the field
        if self.service_led is None and "service_led" in self.model_fields_set:
            _dict['serviceLED'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        # set to None if status_led (nullable) is None
        # and model_fields_set contains the field
        if self.status_led is None and "status_led" in self.model_fields_set:
            _dict['statusLED'] = None

        # set to None if system_id (nullable) is None
        # and model_fields_set contains the field
        if self.system_id is None and "system_id" in self.model_fields_set:
            _dict['systemId'] = None

        # set to None if test_in_progress (nullable) is None
        # and model_fields_set contains the field
        if self.test_in_progress is None and "test_in_progress" in self.model_fields_set:
            _dict['testInProgress'] = None

        # set to None if time_to_charge (nullable) is None
        # and model_fields_set contains the field
        if self.time_to_charge is None and "time_to_charge" in self.model_fields_set:
            _dict['timeToCharge'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodeBatteryDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "associatedLinks": [AssociatedLinksInner.from_dict(_item) for _item in obj["associatedLinks"]] if obj.get("associatedLinks") is not None else None,
            "chargeLevel": obj.get("chargeLevel"),
            "commonResourceAttributes": PrimeraCommonResourceAttributes.from_dict(obj["commonResourceAttributes"]) if obj.get("commonResourceAttributes") is not None else None,
            "consoleUri": obj.get("consoleUri"),
            "customerId": obj.get("customerId"),
            "dischargeLED": obj.get("dischargeLED"),
            "displayname": obj.get("displayname"),
            "domain": obj.get("domain"),
            "expirationDate": ExpirationDate.from_dict(obj["expirationDate"]) if obj.get("expirationDate") is not None else None,
            "faultLED": obj.get("faultLED"),
            "fullyCharged": obj.get("fullyCharged"),
            "generation": obj.get("generation"),
            "id": obj.get("id"),
            "life": obj.get("life"),
            "locateEnabled": obj.get("locateEnabled"),
            "manufacturing": ManufacturingSingle.from_dict(obj["manufacturing"]) if obj.get("manufacturing") is not None else None,
            "maxLife": obj.get("maxLife"),
            "name": obj.get("name"),
            "nodeBatteryId": obj.get("nodeBatteryId"),
            "powerSupplyId": obj.get("powerSupplyId"),
            "primaryNodeId": obj.get("primaryNodeId"),
            "requestUri": obj.get("requestUri"),
            "resourceUri": obj.get("resourceUri"),
            "safeToRemove": obj.get("safeToRemove"),
            "secondaryNodeId": obj.get("secondaryNodeId"),
            "serviceLED": obj.get("serviceLED"),
            "state": STATE.from_dict(obj["state"]) if obj.get("state") is not None else None,
            "statusLED": obj.get("statusLED"),
            "systemId": obj.get("systemId"),
            "testInProgress": obj.get("testInProgress"),
            "timeToCharge": obj.get("timeToCharge"),
            "type": obj.get("type")
        })
        return _obj


